### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/infografia-DuilioAquino10#2]
[Duilio Ruben Aquino Lopez.pdf](https://github.com/SistemasTecTlaxiaco/infografia-DuilioAquino10/files/7125522/Duilio.Ruben.Aquino.Lopez.pdf)

**Comment by IsraelNicolas61** [comment]
¡Buen trabajo!
Calificación: 18/20 puntos

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
